sale/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'sale'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    url(r'^page/(?P<page>\d+)/$', views.IndexView.as_view()),
    path('profile/', views.ProfileView.as_view(), name='user_profile'),
    path('logout/', views.LogoutView, name='logout'),
    path('bets/', views.BetsView.as_view(), name="bets"),
    path('mybets/', views.MyBetsView.as_view(), name='mybets')
]

shop/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.contrib.auth import views as auth_views
from sale import views as core_views

urlpatterns = [
    path('', core_views.IndexView.as_view()),
	path('sale/', include('sale.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.login, name='login'),
    path('signup/', core_views.signup.as_view(), name='signup')
]

sale/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save, pre_init
from django.dispatch import receiver
from django.utils import timezone


class Lot(models.Model):
    STATUSES = (('OPEN', 'Lot is open'),('ACTIVE','Lot active'),('CLOSED', 'Lot is closed'),)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    started = models.DateTimeField('date was issued', default=timezone.now)
    ended = models.DateTimeField('expiration date', default=timezone.now() + timezone.timedelta(days=31))
    status = models.CharField(max_length=100, choices=STATUSES, default='OPEN')
    winner = models.CharField(max_length=200, default='None')
    sum = models.IntegerField(default=1)
    last = models.DateTimeField('last bet', default=timezone.now)

    def check_date():
        q = Lot.objects.filter(status='OPEN')
        for item in q:
            delta = item.ended - timezone.now()
            if delta.total_seconds() < 0:
                item.status = 'CLOSED'
                item.save()

    def can_bet(self, betsum):
        return (betsum > self.sum)

    def __str__(self):
        return self.name
	
class Bet(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    lot = models.ForeignKey(Lot, on_delete=models.CASCADE)
    timestamp = models.DateTimeField('date was issued')
    amount = models.IntegerField()

    def __str__(self):
        return self.lot.description


class Profile(models.Model):
    user = models.OneToOneField(
		settings.AUTH_USER_MODEL,
		related_name="profile",
		verbose_name=("user"),
		on_delete=models.CASCADE,
	)
    amount = models.IntegerField(null=True, blank=True, default=100)
    last_bet = models.DateTimeField(default=timezone.now)

    def time_passed(self, time):
        delta = self.last_bet - time
        print(delta)
        return ( delta.total_seconds() > 30 )

    def enough_money(self, sum):
        return self.amount > sum

    #def __str__(self):
     #   return self.user.name


@receiver(post_save, sender=get_user_model())
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()
        print("Saved")

sale/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from sale.models import Bet

class SignUpForm(UserCreationForm):
    amount = forms.IntegerField(help_text='Required. Enter initial amount')

    class Meta:
        model = User
        fields = ('username', 'email', 'amount', 'password1', 'password2', )

class BetForm(forms.ModelForm):

    class Meta:
        model = Bet
        fields = ('amount',)

sale/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from sale.forms import SignUpForm, BetForm
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.views import View
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .models import Lot, Bet, Profile


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'sale/index.html'
    context_object_name = 'latest_lots_list'
    paginate_by = 12
    Lot.check_date()

    def get_queryset(self):
        list = Lot.objects.filter(status='OPEN').order_by('-started')
        return list

class MyBetsView(LoginRequiredMixin, generic.ListView):
    login_url =  '/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'sale/mybets.html'
    context_object_name = 'my_bets_list'
    paginate_by = 12

    def get_queryset(self):
        list = Bet.objects.filter(owner=self.request.user)
        return list


class BetsView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'sale/bets.html'
    context_object_name = 'all_bets'
    paginate_by = 12

    def get_queryset(self):
        return Bet.objects.order_by('-timestamp')

class DetailView(View):

    template_name = 'sale/detail.html'
    form_class = BetForm
    context_object_name = "lot_info"

    def get(self, request, pk):
        form = BetForm()
        lot = Lot.objects.get(id=pk)
        context = {'form': form, 'lot':lot.name, 'amount':lot.sum, 'winner':lot.winner}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        form = BetForm(request.POST)
        lot = Lot.objects.get(id=pk)
        user = request.user
        print (user.profile.amount)
        if form.is_valid():
            currentbet = form.cleaned_data.get('amount')
            if (lot.can_bet(currentbet)):
                print("can bet")
                if user.profile.enough_money(currentbet):
                    print("enough")
                    if user.profile.time_passed(lot.last):
                        print("TIME passed")
                        bet =  form.save(commit=False)
                        bet.owner = user
                        bet.lot = lot
                        bet.lot.winner = user.username
                        bet.timestamp = timezone.now()
                        bet.lot.sum = currentbet
                        user.profile.amount -= currentbet
                        bet.save()
                        lot.save()
                        user.profile.save()
            return redirect ('sale:index')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['lot'] = Lot.objects.all()
        print(ctx)
        return ctx

class ProfileView(generic.DetailView):

    model = Profile
    template_name = 'sale/myprofile.html'

    def get_object(self):
        return Profile.objects.get(user=self.request.user)

def LogoutView(request):
    logout(request)
    return redirect('sale:index')


class signup(generic.CreateView):

    template_name = 'signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('login')

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            psw = form.cleaned_data['password1']
            user = User.objects.create_user(username, email, psw)
            user.refresh_from_db()
            print('1')
            user.profile.amount = form.cleaned_data.get('amount')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
              # load the profile instance created by the signal
            print('2')

            user.save()



            login(request, user)
            return redirect('sale:index')
        else:
            return HttpResponse('Form is invalid')

    def get(self, request):
        form = SignUpForm()
        context = {'form': form}
        return render(request, self.template_name, context)

sale/templates/Snippets/pagination.html
{% if is_paginated %}

<div class="w3-container w3-indigo w3-display-bottom footer " style="vertical-align: bottom;" >
<div class="w3-bar w3-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}

          <a href="?page={{ page_obj.previous_page_number }}" class="w3-button">
            <span>Previous</span>
          </a>



      {% endif %}

      {% for page in paginator.page_range %}
          <a href="?page={{ page }}" class="w3-button">{{ page }}</a>
        {% endfor %}

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="w3-button">
            <span>Next</span>
          </a>
      {% endif %}
    </ul>
  </div>
</div>
{% endif %}

sale/templates/base.html
<!DOCTYPE html>
<html land="en">

{% load staticfiles %}

<head>
    <title>{% block title %}My great shop site{% endblock %}</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'sale/sale.css' %}">
</head>

<body>

<div class="w3-sidebar w3-light-grey w3-bar-block w3-card" style="width:15%" id="sidebar">
        <h3 class="w3-bar-item">Menu</h3>

        {% block sidebar %}

        <ul>
            <li><a href={% url 'sale:index' %} class="w3-bar-item w3-button">Lots</a></li>
            <li><a href={% url 'sale:bets' %} class="w3-bar-item w3-button">All bets</a></li>
            <li><a href={% url 'sale:mybets' %} class="w3-bar-item w3-button">My bets</a></li>
            <li><a href={% url 'sale:user_profile' %} class="w3-bar-item w3-button">Profile</a></li>
            <li><a href={% url 'login' %} class="w3-bar-item w3-button">Login</a></li>
            <li><a href={% url 'signup' %} class="w3-bar-item w3-button">Sign up</a></li>
            <li><a href={% url 'sale:logout' %} class="w3-bar-item w3-button">Exit</a></li>
        </ul>
        {% endblock %}
</div>


<div style="margin-left:15%">

    <div class="w3-container w3-indigo">
        <div class="w3-left-align"><h1>Auction shop site</h1></div>
        <div class="w3-right-align"><p>Logged in as <b>{{ request.user.username }}</b></p></div>
    </div>



    <div class="w3-container" id="content"">
    {% block content %}{% endblock %}
    </div>

 {% include 'Snippets/pagination.html' %}


</div>




</body>

sale/templates/sale/bets.html
{% extends "base.html" %}


{% block content %}


        {% if all_bets %}
        
        <table class="w3-table w3-striped">
             <tr>
                    <th>Name</th>
                    <th>Bet owner</th>
                    <th>Price</th>
                    <th>Issued</th>
                </tr>
            {% for item in all_bets %}
            <tr> <td>{{ item.lot.name }}</td><td>{{ item.owner.username }}</td><td>{{ item.amount }}</td><td>{{item.timestamp }}</a></td></tr>
            {% endfor %}
        </table>
        {% else %}
            <p>No bets available</p>
        {% endif %}

{% endblock %}

sale/templates/sale/detail.html
{% extends "base.html" %}

{% block content %}


<h3>Active Lot: {{ lot }}</h3>
<p>Maximum bet is: {{ amount }} / Current winner is {{ winner }}</p>




<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Make Bet" />

</form>



{% endblock %}

sale/templates/sale/index.html
{% extends "base.html" %}




{% block content %}

<head>

</head>


{% if latest_lots_list %}
        
        <div class="w3-container" style="height:100%;">
            <table class="w3-table w3-striped">
                 <tr>
                    <th>Name</th>
                    <th>Price</th>
                </tr>
            {% for item in latest_lots_list %}
                <h3><tr><td><a href={% url 'sale:detail' item.id %}>{{ item.name }}</td><td>Current price is {{ item.sum }}</td></h3></tr>
            {% endfor %}
            </table>
        </div>




 {% else %}
            <p>No lots available</p>
 {% endif %}


{% endblock %}

sale/templates/sale/makebet.html
{% extends "base.html" %}


{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">Submit</button>

</form>
<h2>{{ am }}</h2>

{% endblock %}

sale/templates/sale/mybets.html
{% extends "base.html" %}


{% block content %}


{% if my_bets_list %}
        
        <div class="w3-container" style="height:100%;">
            <table class="w3-table w3-striped">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Price</th>
                </tr>
            {% for item in my_bets_list %}
                <h3><tr><td>{{ item.lot.name }} </td><td> {{ item.lot.description }} </td><td> {{ item.lot.status }} </td><td> {{ item.amount }} </td></h3></tr>
            {% endfor %}
            </table>
        </div>




 {% else %}
            <p>You don't have bets</p>
 {% endif %}


{% endblock %}

sale/templates/sale/myprofile.html
{% extends "base.html" %}

{% block content %}



<h3>{{ user.username }}</h3>
<p>First name: {{ user.first_name }}</p>
<p>Last name: {{ user.last_name }}</p>
<p>E-mail: {{ user.email }}</p>
<p>You have {{ user.profile.amount }} dollars</p>






{% endblock %}

sale/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}

<h3>Sign up</h3>
<form method ="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>

{% endblock %}